language: php
php:
  - 5.6
before_script:
  - composer self-update
  - composer update --prefer-dist || composer update --prefer-source
script:
#  - vendor/bin/phpunit
  - rm -v ./vendor/autoload.php ./vendor/composer/!(installed.json)
after_script:
  - vendor/bin/coveralls
cache:
  directories:
    - vendor/
